//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Cnae defines model for Cnae.
type Cnae struct {
	Codigo    *string `json:"codigo,omitempty"`
	Descricao *string `json:"descricao,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// EstabelecimentosAtivo defines model for EstabelecimentosAtivo.
type EstabelecimentosAtivo struct {
	Bairro                    *string             `json:"bairro,omitempty"`
	Cep                       *string             `json:"cep,omitempty"`
	Cnaes                     *[]string           `json:"cnaes,omitempty"`
	CnpjBasico                *string             `json:"cnpj_basico,omitempty"`
	CnpjDv                    *string             `json:"cnpj_dv,omitempty"`
	CnpjOrdem                 *string             `json:"cnpj_ordem,omitempty"`
	Complemento               *string             `json:"complemento,omitempty"`
	CorreioEletronico         *string             `json:"correio_eletronico,omitempty"`
	DataInicioAtividade       *openapi_types.Date `json:"data_inicio_atividade,omitempty"`
	DataSituacaoCadastral     *openapi_types.Date `json:"data_situacao_cadastral,omitempty"`
	DataSituacaoEspecial      *openapi_types.Date `json:"data_situacao_especial,omitempty"`
	Ddd1                      *string             `json:"ddd_1,omitempty"`
	Ddd2                      *string             `json:"ddd_2,omitempty"`
	DddFax                    *string             `json:"ddd_fax,omitempty"`
	Fax                       *string             `json:"fax,omitempty"`
	IdentificadorMatrizFilial *string             `json:"identificador_matriz_filial,omitempty"`
	Logradouro                *string             `json:"logradouro,omitempty"`
	MotivoSituacaoCadastral   *string             `json:"motivo_situacao_cadastral,omitempty"`
	Municipio                 *string             `json:"municipio,omitempty"`
	NomeCidadeExterior        *string             `json:"nome_cidade_exterior,omitempty"`
	NomeFantasia              *string             `json:"nome_fantasia,omitempty"`
	Numero                    *string             `json:"numero,omitempty"`
	Pais                      *string             `json:"pais,omitempty"`
	SituacaoCadastral         *string             `json:"situacao_cadastral,omitempty"`
	SituacaoEspecial          *string             `json:"situacao_especial,omitempty"`
	Telefone1                 *string             `json:"telefone_1,omitempty"`
	Telefone2                 *string             `json:"telefone_2,omitempty"`
	TipoLogradouro            *string             `json:"tipo_logradouro,omitempty"`
	Uf                        *string             `json:"uf,omitempty"`
}

// GetCnaesParams defines parameters for GetCnaes.
type GetCnaesParams struct {
	Nome *string `form:"nome,omitempty" json:"nome,omitempty"`
}

// GetEstabelecimentosAtivosParams defines parameters for GetEstabelecimentosAtivos.
type GetEstabelecimentosAtivosParams struct {
	Municipio string `form:"municipio" json:"municipio"`
	Cnae      string `form:"cnae" json:"cnae"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get CNAEs
	// (GET /cnaes)
	GetCnaes(w http.ResponseWriter, r *http.Request, params GetCnaesParams)
	// Get CNAE by code
	// (GET /cnaes/{codigo})
	GetCnaesCodigo(w http.ResponseWriter, r *http.Request, codigo string)
	// Get establishments
	// (GET /estabelecimentos-ativos)
	GetEstabelecimentosAtivos(w http.ResponseWriter, r *http.Request, params GetEstabelecimentosAtivosParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCnaes operation middleware
func (siw *ServerInterfaceWrapper) GetCnaes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCnaesParams

	// ------------- Optional query parameter "nome" -------------

	err = runtime.BindQueryParameter("form", true, false, "nome", r.URL.Query(), &params.Nome)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nome", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCnaes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCnaesCodigo operation middleware
func (siw *ServerInterfaceWrapper) GetCnaesCodigo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "codigo" -------------
	var codigo string

	err = runtime.BindStyledParameterWithOptions("simple", "codigo", r.PathValue("codigo"), &codigo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "codigo", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCnaesCodigo(w, r, codigo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEstabelecimentosAtivos operation middleware
func (siw *ServerInterfaceWrapper) GetEstabelecimentosAtivos(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEstabelecimentosAtivosParams

	// ------------- Required query parameter "municipio" -------------

	if paramValue := r.URL.Query().Get("municipio"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "municipio"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "municipio", r.URL.Query(), &params.Municipio)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "municipio", Err: err})
		return
	}

	// ------------- Required query parameter "cnae" -------------

	if paramValue := r.URL.Query().Get("cnae"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cnae"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "cnae", r.URL.Query(), &params.Cnae)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cnae", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEstabelecimentosAtivos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/cnaes", wrapper.GetCnaes)
	m.HandleFunc("GET "+options.BaseURL+"/cnaes/{codigo}", wrapper.GetCnaesCodigo)
	m.HandleFunc("GET "+options.BaseURL+"/estabelecimentos-ativos", wrapper.GetEstabelecimentosAtivos)

	return m
}

type GetCnaesRequestObject struct {
	Params GetCnaesParams
}

type GetCnaesResponseObject interface {
	VisitGetCnaesResponse(w http.ResponseWriter) error
}

type GetCnaes200JSONResponse []Cnae

func (response GetCnaes200JSONResponse) VisitGetCnaesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCnaes500JSONResponse Error

func (response GetCnaes500JSONResponse) VisitGetCnaesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCnaesCodigoRequestObject struct {
	Codigo string `json:"codigo"`
}

type GetCnaesCodigoResponseObject interface {
	VisitGetCnaesCodigoResponse(w http.ResponseWriter) error
}

type GetCnaesCodigo200JSONResponse Cnae

func (response GetCnaesCodigo200JSONResponse) VisitGetCnaesCodigoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCnaesCodigo404JSONResponse Error

func (response GetCnaesCodigo404JSONResponse) VisitGetCnaesCodigoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCnaesCodigo500JSONResponse Error

func (response GetCnaesCodigo500JSONResponse) VisitGetCnaesCodigoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEstabelecimentosAtivosRequestObject struct {
	Params GetEstabelecimentosAtivosParams
}

type GetEstabelecimentosAtivosResponseObject interface {
	VisitGetEstabelecimentosAtivosResponse(w http.ResponseWriter) error
}

type GetEstabelecimentosAtivos200JSONResponse []EstabelecimentosAtivo

func (response GetEstabelecimentosAtivos200JSONResponse) VisitGetEstabelecimentosAtivosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEstabelecimentosAtivos500JSONResponse Error

func (response GetEstabelecimentosAtivos500JSONResponse) VisitGetEstabelecimentosAtivosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get CNAEs
	// (GET /cnaes)
	GetCnaes(ctx context.Context, request GetCnaesRequestObject) (GetCnaesResponseObject, error)
	// Get CNAE by code
	// (GET /cnaes/{codigo})
	GetCnaesCodigo(ctx context.Context, request GetCnaesCodigoRequestObject) (GetCnaesCodigoResponseObject, error)
	// Get establishments
	// (GET /estabelecimentos-ativos)
	GetEstabelecimentosAtivos(ctx context.Context, request GetEstabelecimentosAtivosRequestObject) (GetEstabelecimentosAtivosResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCnaes operation middleware
func (sh *strictHandler) GetCnaes(w http.ResponseWriter, r *http.Request, params GetCnaesParams) {
	var request GetCnaesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCnaes(ctx, request.(GetCnaesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCnaes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCnaesResponseObject); ok {
		if err := validResponse.VisitGetCnaesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCnaesCodigo operation middleware
func (sh *strictHandler) GetCnaesCodigo(w http.ResponseWriter, r *http.Request, codigo string) {
	var request GetCnaesCodigoRequestObject

	request.Codigo = codigo

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCnaesCodigo(ctx, request.(GetCnaesCodigoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCnaesCodigo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCnaesCodigoResponseObject); ok {
		if err := validResponse.VisitGetCnaesCodigoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEstabelecimentosAtivos operation middleware
func (sh *strictHandler) GetEstabelecimentosAtivos(w http.ResponseWriter, r *http.Request, params GetEstabelecimentosAtivosParams) {
	var request GetEstabelecimentosAtivosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEstabelecimentosAtivos(ctx, request.(GetEstabelecimentosAtivosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEstabelecimentosAtivos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEstabelecimentosAtivosResponseObject); ok {
		if err := validResponse.VisitGetEstabelecimentosAtivosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWTW8bNxD9K8K0RzVy3PSyN8NIirRAekiBHgxjMSJnpTF2OcxwVohq7H8vuGtZbsWN",
	"5QIp0Jy04nyS7/EN78FJFyVQsATVPSS3pQ7Hz+uAlH+jSiQ1pnHVieeN5C/bR4IKkimHDQxL8JScssOS",
	"dVgeVmR9R86y/1tV0dMKHaWEGyonUfrUs5KH6ubR8baUOxmuqSXHHQWTdGW8k9Naa2TV8m4cxfJ6wCmW",
	"jbpUdHlYQFXcTyHxrl5jYjdTKtv9bt4m6qkrm6WLLY17nLGrEktNLZlKmOvAo2HNgR1LjcY79uhHBBrR",
	"Dg2q7EGwnIlMbD06lNqhx2SK7b+IpRTJ8bmh3tevy1vxvr6ctTT4uWibW2dPwbhhh1607tCU/6wbbh/6",
	"PPFvZaPopZ8hVSeZhzPnderdZ0Qil3MF6ah2I1I1fTZSnm5T2bHBYJgYyx59RzMdR+Qyyc/cQxHe0xtD",
	"LTUSaAbTR3MZWOMo9TMn3zdnqVLumFyvbPuPWQofZIJQSa962x7/vTtQ9Jc/foflJJw502Q9cnZrFmHI",
	"iTk0AlXo23YJEilgZKjgx1cXry4hH7Rtx2KrR4XZkOWfLFhoLOG9hwp+JrseHXKIYkdGmqC6uQcOUMGn",
	"nnQPSwg4dpOxP3RXwn64zZqaooQ01by8uJhkPhiFsTzG2LIbG1jdJQnHMfE3FfxeqYEKvlsdB8rqYZqs",
	"xlFyIozD48yIOTlU8Nuv2eunF7bwpcrTjCmUeh+MNGC7+Ei6I10cHI/4j2f6FPmb23xaqe861P2ExOL6",
	"w9XbNIZNsK3upwE5PIvf9TRIyyhmMhxBdAfX4/Qz7elrwvo8mnPovbl48/XR+yC2eCd98P9HvizW+4UT",
	"TxNt6B8vlR/y/JUv3v/i4+ZMQTjOlJfQaVlOlin/clo+ecE9aWbM9Z+oUflt+E3K00iultO2Gx/4w5Qg",
	"Z5wY0msLFaww8mr3Gobb4a8AAAD///AUuZgQDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
