// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cnaes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCnae = `-- name: CreateCnae :exec
INSERT INTO cnaes (
    codigo,
    descricao
) VALUES (
    $1, $2
)
`

type CreateCnaeParams struct {
	Codigo    string
	Descricao pgtype.Text
}

func (q *Queries) CreateCnae(ctx context.Context, arg CreateCnaeParams) error {
	_, err := q.db.Exec(ctx, createCnae, arg.Codigo, arg.Descricao)
	return err
}
