// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: empresas.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmpresa = `-- name: CreateEmpresa :exec
INSERT INTO empresas (
    cnpj_basico,
    razao_social,
    natureza_juridica,
    qualificacao_responsavel,
    capital_social,
    porte,
    ente_federativo_responsavel
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateEmpresaParams struct {
	CnpjBasico                string
	RazaoSocial               pgtype.Text
	NaturezaJuridica          pgtype.Text
	QualificacaoResponsavel   pgtype.Text
	CapitalSocial             pgtype.Numeric
	Porte                     pgtype.Text
	EnteFederativoResponsavel pgtype.Text
}

func (q *Queries) CreateEmpresa(ctx context.Context, arg CreateEmpresaParams) error {
	_, err := q.db.Exec(ctx, createEmpresa,
		arg.CnpjBasico,
		arg.RazaoSocial,
		arg.NaturezaJuridica,
		arg.QualificacaoResponsavel,
		arg.CapitalSocial,
		arg.Porte,
		arg.EnteFederativoResponsavel,
	)
	return err
}
