// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estabelecimentos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEstabelecimento = `-- name: CreateEstabelecimento :exec
INSERT INTO estabelecimentos (
    cnpj_basico,
    cnpj_ordem,
    cnpj_dv,
    identificador_matriz_filial,
    nome_fantasia,
    situacao_cadastral,
    data_situacao_cadastral,
    motivo_situacao_cadastral,
    nome_cidade_exterior,
    pais,
    data_inicio_atividade,
    cnae_fiscal_principal,
    cnae_fiscal_secundaria,
    tipo_logradouro,
    logradouro,
    numero,
    complemento,
    bairro,
    cep,
    uf,
    municipio,
    ddd_1,
    telefone_1,
    ddd_2,
    telefone_2,
    ddd_fax,
    fax,
    correio_eletronico,
    situacao_especial,
    data_situacao_especial
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30
)
`

type CreateEstabelecimentoParams struct {
	CnpjBasico                string
	CnpjOrdem                 string
	CnpjDv                    string
	IdentificadorMatrizFilial pgtype.Text
	NomeFantasia              pgtype.Text
	SituacaoCadastral         pgtype.Text
	DataSituacaoCadastral     pgtype.Date
	MotivoSituacaoCadastral   pgtype.Text
	NomeCidadeExterior        pgtype.Text
	Pais                      pgtype.Text
	DataInicioAtividade       pgtype.Date
	CnaeFiscalPrincipal       pgtype.Text
	CnaeFiscalSecundaria      pgtype.Text
	TipoLogradouro            pgtype.Text
	Logradouro                pgtype.Text
	Numero                    pgtype.Text
	Complemento               pgtype.Text
	Bairro                    pgtype.Text
	Cep                       pgtype.Text
	Uf                        pgtype.Text
	Municipio                 pgtype.Text
	Ddd1                      pgtype.Text
	Telefone1                 pgtype.Text
	Ddd2                      pgtype.Text
	Telefone2                 pgtype.Text
	DddFax                    pgtype.Text
	Fax                       pgtype.Text
	CorreioEletronico         pgtype.Text
	SituacaoEspecial          pgtype.Text
	DataSituacaoEspecial      pgtype.Date
}

func (q *Queries) CreateEstabelecimento(ctx context.Context, arg CreateEstabelecimentoParams) error {
	_, err := q.db.Exec(ctx, createEstabelecimento,
		arg.CnpjBasico,
		arg.CnpjOrdem,
		arg.CnpjDv,
		arg.IdentificadorMatrizFilial,
		arg.NomeFantasia,
		arg.SituacaoCadastral,
		arg.DataSituacaoCadastral,
		arg.MotivoSituacaoCadastral,
		arg.NomeCidadeExterior,
		arg.Pais,
		arg.DataInicioAtividade,
		arg.CnaeFiscalPrincipal,
		arg.CnaeFiscalSecundaria,
		arg.TipoLogradouro,
		arg.Logradouro,
		arg.Numero,
		arg.Complemento,
		arg.Bairro,
		arg.Cep,
		arg.Uf,
		arg.Municipio,
		arg.Ddd1,
		arg.Telefone1,
		arg.Ddd2,
		arg.Telefone2,
		arg.DddFax,
		arg.Fax,
		arg.CorreioEletronico,
		arg.SituacaoEspecial,
		arg.DataSituacaoEspecial,
	)
	return err
}
