// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cnae struct {
	Codigo    string
	Descricao pgtype.Text
}

type Empresa struct {
	CnpjBasico                string
	RazaoSocial               pgtype.Text
	NaturezaJuridica          pgtype.Text
	QualificacaoResponsavel   pgtype.Text
	CapitalSocial             pgtype.Numeric
	Porte                     pgtype.Text
	EnteFederativoResponsavel pgtype.Text
}

type Estabelecimento struct {
	CnpjBasico                string
	CnpjOrdem                 string
	CnpjDv                    string
	IdentificadorMatrizFilial pgtype.Text
	NomeFantasia              pgtype.Text
	SituacaoCadastral         pgtype.Text
	DataSituacaoCadastral     pgtype.Date
	MotivoSituacaoCadastral   pgtype.Text
	NomeCidadeExterior        pgtype.Text
	Pais                      pgtype.Text
	DataInicioAtividade       pgtype.Date
	CnaeFiscalPrincipal       pgtype.Text
	CnaeFiscalSecundaria      pgtype.Text
	TipoLogradouro            pgtype.Text
	Logradouro                pgtype.Text
	Numero                    pgtype.Text
	Complemento               pgtype.Text
	Bairro                    pgtype.Text
	Cep                       pgtype.Text
	Uf                        pgtype.Text
	Municipio                 pgtype.Text
	Ddd1                      pgtype.Text
	Telefone1                 pgtype.Text
	Ddd2                      pgtype.Text
	Telefone2                 pgtype.Text
	DddFax                    pgtype.Text
	Fax                       pgtype.Text
	CorreioEletronico         pgtype.Text
	SituacaoEspecial          pgtype.Text
	DataSituacaoEspecial      pgtype.Date
}

type EstabelecimentosAtivo struct {
	CnpjBasico                string
	CnpjOrdem                 string
	CnpjDv                    string
	IdentificadorMatrizFilial pgtype.Text
	NomeFantasia              pgtype.Text
	SituacaoCadastral         pgtype.Text
	DataSituacaoCadastral     pgtype.Date
	MotivoSituacaoCadastral   pgtype.Text
	NomeCidadeExterior        pgtype.Text
	Pais                      pgtype.Text
	DataInicioAtividade       pgtype.Date
	Cnaes                     []string
	TipoLogradouro            pgtype.Text
	Logradouro                pgtype.Text
	Numero                    pgtype.Text
	Complemento               pgtype.Text
	Bairro                    pgtype.Text
	Cep                       pgtype.Text
	Uf                        pgtype.Text
	Municipio                 pgtype.Text
	Ddd1                      pgtype.Text
	Telefone1                 pgtype.Text
	Ddd2                      pgtype.Text
	Telefone2                 pgtype.Text
	DddFax                    pgtype.Text
	Fax                       pgtype.Text
	CorreioEletronico         pgtype.Text
	SituacaoEspecial          pgtype.Text
	DataSituacaoEspecial      pgtype.Date
}

type Motivo struct {
	Codigo    string
	Descricao pgtype.Text
}

type Municipio struct {
	Codigo    string
	Descricao pgtype.Text
}

type NaturezasJuridica struct {
	Codigo    string
	Descricao pgtype.Text
}

type Paise struct {
	Codigo    string
	Descricao pgtype.Text
}

type QualificacoesDeSocio struct {
	Codigo    string
	Descricao pgtype.Text
}

type Simple struct {
	CnpjBasico            string
	OpcaoPeloSimples      pgtype.Text
	DataOpcaoPeloSimples  pgtype.Date
	DataExclusaoDoSimples pgtype.Date
	OpcaoPeloMei          pgtype.Text
	DataOpcaoPeloMei      pgtype.Date
	DataExclusaoDoMei     pgtype.Date
}

type Socio struct {
	CnpjBasico                     pgtype.Text
	IdentificadorDeSocio           pgtype.Text
	NomeSocio                      pgtype.Text
	CnpjCpfSocio                   pgtype.Text
	QualificacaoSocio              pgtype.Text
	DataEntradaSociedade           pgtype.Date
	Pais                           pgtype.Text
	RepresentanteLegal             pgtype.Text
	NomeRepresentante              pgtype.Text
	QualificacaoRepresentanteLegal pgtype.Text
	FaixaEtaria                    pgtype.Text
}
