// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: motivos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMotivo = `-- name: CreateMotivo :exec
INSERT INTO motivos (
    codigo,
    descricao
) VALUES (
    $1, $2
)
`

type CreateMotivoParams struct {
	Codigo    string
	Descricao pgtype.Text
}

func (q *Queries) CreateMotivo(ctx context.Context, arg CreateMotivoParams) error {
	_, err := q.db.Exec(ctx, createMotivo, arg.Codigo, arg.Descricao)
	return err
}
