// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: municipios.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMunicipio = `-- name: CreateMunicipio :exec
INSERT INTO municipios (
    codigo,
    descricao
) VALUES (
    $1, $2
)
`

type CreateMunicipioParams struct {
	Codigo    string
	Descricao pgtype.Text
}

func (q *Queries) CreateMunicipio(ctx context.Context, arg CreateMunicipioParams) error {
	_, err := q.db.Exec(ctx, createMunicipio, arg.Codigo, arg.Descricao)
	return err
}
