// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: naturezas_juridicas.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNaturezaJuridica = `-- name: CreateNaturezaJuridica :exec
INSERT INTO naturezas_juridicas (
    codigo,
    descricao
) VALUES (
    $1, $2
)
`

type CreateNaturezaJuridicaParams struct {
	Codigo    string
	Descricao pgtype.Text
}

func (q *Queries) CreateNaturezaJuridica(ctx context.Context, arg CreateNaturezaJuridicaParams) error {
	_, err := q.db.Exec(ctx, createNaturezaJuridica, arg.Codigo, arg.Descricao)
	return err
}
