// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paises.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPais = `-- name: CreatePais :exec
INSERT INTO paises (
    codigo,
    descricao
) VALUES (
    $1, $2
)
`

type CreatePaisParams struct {
	Codigo    string
	Descricao pgtype.Text
}

func (q *Queries) CreatePais(ctx context.Context, arg CreatePaisParams) error {
	_, err := q.db.Exec(ctx, createPais, arg.Codigo, arg.Descricao)
	return err
}
