// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qualificacoes_de_socios.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQualificacaoSocio = `-- name: CreateQualificacaoSocio :exec
INSERT INTO qualificacoes_de_socios (
    codigo,
    descricao
) VALUES (
    $1, $2
)
`

type CreateQualificacaoSocioParams struct {
	Codigo    string
	Descricao pgtype.Text
}

func (q *Queries) CreateQualificacaoSocio(ctx context.Context, arg CreateQualificacaoSocioParams) error {
	_, err := q.db.Exec(ctx, createQualificacaoSocio, arg.Codigo, arg.Descricao)
	return err
}
