// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: simples.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSimples = `-- name: CreateSimples :exec
INSERT INTO simples (
    cnpj_basico,
    opcao_pelo_simples,
    data_opcao_pelo_simples,
    data_exclusao_do_simples,
    opcao_pelo_mei,
    data_opcao_pelo_mei,
    data_exclusao_do_mei
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateSimplesParams struct {
	CnpjBasico            string
	OpcaoPeloSimples      pgtype.Text
	DataOpcaoPeloSimples  pgtype.Date
	DataExclusaoDoSimples pgtype.Date
	OpcaoPeloMei          pgtype.Text
	DataOpcaoPeloMei      pgtype.Date
	DataExclusaoDoMei     pgtype.Date
}

func (q *Queries) CreateSimples(ctx context.Context, arg CreateSimplesParams) error {
	_, err := q.db.Exec(ctx, createSimples,
		arg.CnpjBasico,
		arg.OpcaoPeloSimples,
		arg.DataOpcaoPeloSimples,
		arg.DataExclusaoDoSimples,
		arg.OpcaoPeloMei,
		arg.DataOpcaoPeloMei,
		arg.DataExclusaoDoMei,
	)
	return err
}
