// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: socios.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSocio = `-- name: CreateSocio :exec
INSERT INTO socios (
    cnpj_basico,
    identificador_de_socio,
    nome_socio,
    cnpj_cpf_socio,
    qualificacao_socio,
    data_entrada_sociedade,
    pais,
    representante_legal,
    nome_representante,
    qualificacao_representante_legal,
    faixa_etaria
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateSocioParams struct {
	CnpjBasico                     pgtype.Text
	IdentificadorDeSocio           pgtype.Text
	NomeSocio                      pgtype.Text
	CnpjCpfSocio                   pgtype.Text
	QualificacaoSocio              pgtype.Text
	DataEntradaSociedade           pgtype.Date
	Pais                           pgtype.Text
	RepresentanteLegal             pgtype.Text
	NomeRepresentante              pgtype.Text
	QualificacaoRepresentanteLegal pgtype.Text
	FaixaEtaria                    pgtype.Text
}

func (q *Queries) CreateSocio(ctx context.Context, arg CreateSocioParams) error {
	_, err := q.db.Exec(ctx, createSocio,
		arg.CnpjBasico,
		arg.IdentificadorDeSocio,
		arg.NomeSocio,
		arg.CnpjCpfSocio,
		arg.QualificacaoSocio,
		arg.DataEntradaSociedade,
		arg.Pais,
		arg.RepresentanteLegal,
		arg.NomeRepresentante,
		arg.QualificacaoRepresentanteLegal,
		arg.FaixaEtaria,
	)
	return err
}
